# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ot-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://otacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8bc26a872219490f9b6ee48e5971aa15 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8ef37c01f67a4d08be255eeb3d0ad1d8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: otacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8bc26a872219490f9b6ee48e5971aa15 }}/ot-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ot-back'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7636dcb95c69462bbfa98992aff1295b }}
        images: 'otacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8bc26a872219490f9b6ee48e5971aa15 }}/ot-backend:${{ github.sha }}'